name: flutter11
description: "A new Flutter project."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.12.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  moon_design: ^1.1.0
  shadcn_ui: ^0.54.0
  wave_animation: ^1.0.4
  forui: ^0.22.3
  forui_assets: ^0.22.1
  flutter_svg: ^2.3.0
  floating_menu_panel: ^0.0.2
  flutter_floating_bottom_bar: ^2.0.0
  floating_bottom_bar: ^0.0.4
  animated_notch_bottom_bar: ^1.0.4
  curved_navigation_bar: ^1.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/tropfen.svg
